openapi: 3.2.0
info:
  description: 'The setlist.fm API has been designed to give you easy access to setlist data in order to build fancy websites and

    other applications.'
  version: '1.0'
  title: setlist.fm /1.0/search/artists API
servers:
- url: /rest
tags:
- name: /1.0/search/artists
paths:
  /1.0/search/artists:
    get:
      tags:
      - /1.0/search/artists
      summary: Search for artists
      description: Search for artists.
      operationId: resource__1.0_search_artists_getArtists_GET
      parameters:
      - name: artistMbid
        in: query
        description: the artist's Musicbrainz Identifier (mbid)
        schema:
          type: string
      - name: artistName
        in: query
        description: the artist's name
        schema:
          type: string
      - name: artistTmid
        in: query
        description: the artist's Ticketmaster Identifier (tmid) (deprecated)
        schema:
          type: integer
      - name: p
        in: query
        description: the number of the result page you'd like to have
        schema:
          type: integer
          default: '1'
      - name: sort
        in: query
        description: the sort of the result, either sortName (default) or relevance
        schema:
          type: string
          default: sortName
      responses:
        '200':
          headers: {}
          description: Success
          content:
            application/xml:
              schema:
                description: ''
                $ref: '#/components/schemas/json_Artists'
            application/json:
              schema:
                description: ''
                $ref: '#/components/schemas/json_Artists'
              example:
                artist:
                - mbid: b10bbbfc-cf9e-42e0-be17-e2c3e1d2600d
                  name: The Beatles
                  sortName: Beatles, The
                  disambiguation: John, Paul, George and Ringo
                  url: https://www.setlist.fm/setlists/the-beatles-23d6a88b.html
                - mbid: '...'
                  name: '...'
                  sortName: '...'
                  disambiguation: '...'
                  url: '...'
                total: 42
                page: 1
                itemsPerPage: 20
components:
  schemas:
    json_Artist:
      type: object
      title: artist
      properties:
        mbid:
          example: b10bbbfc-cf9e-42e0-be17-e2c3e1d2600d
          description: unique Musicbrainz Identifier (MBID), e.g. <em>&quot;b10bbbfc-cf9e-42e0-be17-e2c3e1d2600d&quot;</em>
          type: string
        tmid:
          example: 735610
          description: unique Ticket Master Identifier (TMID), e.g. <em>735610</em> (deprecated)
          type: number
        name:
          example: The Beatles
          description: the artist's name, e.g. <em>&quot;The Beatles&quot;</em>
          type: string
        sortName:
          example: Beatles, The
          description: the artist's sort name, e.g. <em>&quot;Beatles, The&quot;</em> or <em>&quot;Springsteen, Bruce&quot;</em>
          type: string
        disambiguation:
          example: John, Paul, George and Ringo
          description: disambiguation to distinguish between artists with same names
          type: string
        url:
          example: https://www.setlist.fm/setlists/the-beatles-23d6a88b.html
          description: the attribution url
          type: string
      example:
        mbid: b10bbbfc-cf9e-42e0-be17-e2c3e1d2600d
        name: The Beatles
        sortName: Beatles, The
        disambiguation: John, Paul, George and Ringo
        url: https://www.setlist.fm/setlists/the-beatles-23d6a88b.html
      description: 'This class represents an artist. An artist is a musician or a group of musicians. Each artist has a definite

        <a href="http://wiki.musicbrainz.org/MBID">Musicbrainz Identifier</a> (MBID) with which the artist can be uniquely

        identified.'
    json_Artists:
      type: object
      title: artists
      properties:
        artist:
          description: result list of artists
          type: array
          items:
            $ref: '#/components/schemas/json_Artist'
        total:
          example: 42
          description: the total amount of items matching the query
          type: number
        page:
          example: 1
          description: the current page. starts at 1
          type: number
        itemsPerPage:
          example: 20
          description: the amount of items you get per page
          type: number
      example:
        artist:
        - mbid: b10bbbfc-cf9e-42e0-be17-e2c3e1d2600d
          name: The Beatles
          sortName: Beatles, The
          disambiguation: John, Paul, George and Ringo
          url: https://www.setlist.fm/setlists/the-beatles-23d6a88b.html
        - mbid: '...'
          name: '...'
          sortName: '...'
          disambiguation: '...'
          url: '...'
        total: 42
        page: 1
        itemsPerPage: 20
      description: A Result consisting of a list of artists.
