openapi: 3.2.0
info:
  description: 'The setlist.fm API has been designed to give you easy access to setlist data in order to build fancy websites and

    other applications.'
  version: '1.0'
  title: setlist.fm /1.0/search/cities API
servers:
- url: /rest
tags:
- name: /1.0/search/cities
paths:
  /1.0/search/cities:
    get:
      tags:
      - /1.0/search/cities
      summary: Search for a city
      description: Search for a city.
      operationId: resource__1.0_search_cities_getCities_GET
      parameters:
      - name: country
        in: query
        description: the city's country
        schema:
          type: string
      - name: name
        in: query
        description: name of the city
        schema:
          type: string
      - name: p
        in: query
        description: the number of the result page you'd like to have
        schema:
          type: integer
          default: '1'
      - name: state
        in: query
        description: state the city lies in
        schema:
          type: string
      - name: stateCode
        in: query
        description: state code the city lies in
        schema:
          type: string
      responses:
        '200':
          headers: {}
          description: Success
          content:
            application/xml:
              schema:
                description: ''
                $ref: '#/components/schemas/json_Cities'
            application/json:
              schema:
                description: ''
                $ref: '#/components/schemas/json_Cities'
              example:
                cities:
                - id: '5357527'
                  name: Hollywood
                  stateCode: CA
                  state: California
                  coords:
                    long: -118.3267434
                    lat: 34.0983425
                  country:
                    code: US
                    name: United States
                - id: '...'
                  name: '...'
                  stateCode: '...'
                  state: '...'
                  coords:
                    long: 12345.0
                    lat: 12345.0
                  country:
                    code: '...'
                    name: '...'
                total: 42
                page: 1
                itemsPerPage: 20
components:
  schemas:
    json_Country:
      type: object
      title: country
      properties:
        code:
          example: US
          description: 'The country''s <a href= "http://www.iso.org/iso/english_country_names_and_code_elements" >ISO code</a>. E.g.

            <em>&quot;ie&quot;</em> for Ireland'
          type: string
        name:
          example: United States
          description: 'The country''s name. Can be a localized name - e.g. <em>&quot;Austria&quot;</em> or

            <em>&quot;&Ouml;sterreich&quot;</em> for Austria if the German name was requested.'
          type: string
      example:
        code: US
        name: United States
      description: This class represents a country on earth.
    json_City:
      type: object
      title: city
      properties:
        id:
          example: '5357527'
          description: unique identifier
          type: string
        name:
          example: Hollywood
          description: 'the city''s name, depending on the language valid values are e.g. <em>&quot;M&uuml;chen&quot;</em> or

            <em>Munich</em>'
          type: string
        stateCode:
          example: CA
          description: 'The code of the city''s state. For most countries this is a two-digit numeric code, with which the state can be

            identified uniquely in the specific Country. The code can also be a String for other cities. Valid

            examples are <em>&quot;CA&quot;</em> or <em>&quot;02&quot;</em>


            which in turn get uniquely identifiable when combined with the state''s country:


            <em>&quot;US.CA&quot;</em> for California, United States or <em>&quot;DE.02&quot;</em> for Bavaria, Germany


            For a complete list of available states (that aren''t necessarily used in this database) is available in

            <a href= "http://download.geonames.org/export/dump/admin1CodesASCII.txt">a textfile on geonames.org</a>.


            Note that this code is only unique combined with the city''s Country. The code alone is

            <strong>not</strong> unique.'
          type: string
        state:
          example: California
          description: The name of city's state, e.g. <em>&quot;Bavaria&quot;</em> or <em>&quot;Florida&quot;</em>
          type: string
        coords:
          description: The city's coordinates. Usually the coordinates of the city centre are used.
          $ref: '#/components/schemas/json_Coords'
        country:
          description: The city's country.
          $ref: '#/components/schemas/json_Country'
      example:
        id: '5357527'
        name: Hollywood
        stateCode: CA
        state: California
        coords:
          long: -118.3267434
          lat: 34.0983425
        country:
          code: US
          name: United States
      description: 'This class represents a city where Venues are located. Most of the original city data was taken from

        <a href="http://geonames.org/">Geonames.org</a>.'
    json_Cities:
      type: object
      title: cities
      properties:
        cities:
          description: result list of cities
          type: array
          items:
            $ref: '#/components/schemas/json_City'
        total:
          example: 42
          description: the total amount of items matching the query
          type: number
        page:
          example: 1
          description: the current page. starts at 1
          type: number
        itemsPerPage:
          example: 20
          description: the amount of items you get per page
          type: number
      example:
        cities:
        - id: '5357527'
          name: Hollywood
          stateCode: CA
          state: California
          coords:
            long: -118.3267434
            lat: 34.0983425
          country:
            code: US
            name: United States
        - id: '...'
          name: '...'
          stateCode: '...'
          state: '...'
          coords:
            long: 12345.0
            lat: 12345.0
          country:
            code: '...'
            name: '...'
        total: 42
        page: 1
        itemsPerPage: 20
      description: A Result consisting of a list of cities.
    json_Coords:
      type: object
      title: coords
      properties:
        long:
          example: -118.3267434
          description: The longitude part of the coordinates.
          type: number
        lat:
          example: 34.0983425
          description: The latitude part of the coordinates.
          type: number
      example:
        long: -118.3267434
        lat: 34.0983425
      description: Coordinates of a point on the globe. Mostly used for Cities.
