openapi: 3.2.0
info:
  description: 'The setlist.fm API has been designed to give you easy access to setlist data in order to build fancy websites and

    other applications.'
  version: '1.0'
  title: setlist.fm /1.0/venue/{venue Id} API
servers:
- url: /rest
tags:
- name: /1.0/venue/{venueId}
paths:
  /1.0/venue/{venueId}:
    get:
      tags:
      - /1.0/venue/{venueId}
      summary: Get a venue by its unique id
      description: Get a venue by its unique id.
      operationId: resource__1.0_venue__venueId__getVenue_GET
      parameters:
      - name: venueId
        in: path
        required: true
        description: the venue's id
        schema:
          type: string
      responses:
        '200':
          headers: {}
          description: Success
          content:
            application/xml:
              schema:
                description: ''
                $ref: '#/components/schemas/json_Venue'
            application/json:
              schema:
                description: ''
                $ref: '#/components/schemas/json_Venue'
              example:
                city:
                  id: '5357527'
                  name: Hollywood
                  stateCode: CA
                  state: California
                  coords:
                    long: -118.3267434
                    lat: 34.0983425
                  country:
                    code: US
                    name: United States
                url: https://www.setlist.fm/venue/compaq-center-san-jose-ca-usa-6bd6ca6e.html
                id: 6bd6ca6e
                name: Compaq Center
components:
  schemas:
    json_Venue:
      type: object
      title: venue
      properties:
        city:
          description: the city in which the venue is located
          $ref: '#/components/schemas/json_City'
        url:
          example: https://www.setlist.fm/venue/compaq-center-san-jose-ca-usa-6bd6ca6e.html
          description: the attribution url
          type: string
        id:
          example: 6bd6ca6e
          description: unique identifier
          type: string
        name:
          example: Compaq Center
          description: 'the name of the venue, usually without city and country. E.g. <em>&quot;Madison Square Garden&quot;</em> or

            <em>&quot;Royal Albert Hall&quot;</em>'
          type: string
      example:
        city:
          id: '5357527'
          name: Hollywood
          stateCode: CA
          state: California
          coords:
            long: -118.3267434
            lat: 34.0983425
          country:
            code: US
            name: United States
        url: https://www.setlist.fm/venue/compaq-center-san-jose-ca-usa-6bd6ca6e.html
        id: 6bd6ca6e
        name: Compaq Center
      description: 'Venues are places where concerts take place. They usually consist of a venue name and a city - but there are also

        some venues that do not have a city attached yet. In such a case, the city simply isn''t set and the city and country

        may (but do not have to) be in the name.'
    json_Country:
      type: object
      title: country
      properties:
        code:
          example: US
          description: 'The country''s <a href= "http://www.iso.org/iso/english_country_names_and_code_elements" >ISO code</a>. E.g.

            <em>&quot;ie&quot;</em> for Ireland'
          type: string
        name:
          example: United States
          description: 'The country''s name. Can be a localized name - e.g. <em>&quot;Austria&quot;</em> or

            <em>&quot;&Ouml;sterreich&quot;</em> for Austria if the German name was requested.'
          type: string
      example:
        code: US
        name: United States
      description: This class represents a country on earth.
    json_City:
      type: object
      title: city
      properties:
        id:
          example: '5357527'
          description: unique identifier
          type: string
        name:
          example: Hollywood
          description: 'the city''s name, depending on the language valid values are e.g. <em>&quot;M&uuml;chen&quot;</em> or

            <em>Munich</em>'
          type: string
        stateCode:
          example: CA
          description: 'The code of the city''s state. For most countries this is a two-digit numeric code, with which the state can be

            identified uniquely in the specific Country. The code can also be a String for other cities. Valid

            examples are <em>&quot;CA&quot;</em> or <em>&quot;02&quot;</em>


            which in turn get uniquely identifiable when combined with the state''s country:


            <em>&quot;US.CA&quot;</em> for California, United States or <em>&quot;DE.02&quot;</em> for Bavaria, Germany


            For a complete list of available states (that aren''t necessarily used in this database) is available in

            <a href= "http://download.geonames.org/export/dump/admin1CodesASCII.txt">a textfile on geonames.org</a>.


            Note that this code is only unique combined with the city''s Country. The code alone is

            <strong>not</strong> unique.'
          type: string
        state:
          example: California
          description: The name of city's state, e.g. <em>&quot;Bavaria&quot;</em> or <em>&quot;Florida&quot;</em>
          type: string
        coords:
          description: The city's coordinates. Usually the coordinates of the city centre are used.
          $ref: '#/components/schemas/json_Coords'
        country:
          description: The city's country.
          $ref: '#/components/schemas/json_Country'
      example:
        id: '5357527'
        name: Hollywood
        stateCode: CA
        state: California
        coords:
          long: -118.3267434
          lat: 34.0983425
        country:
          code: US
          name: United States
      description: 'This class represents a city where Venues are located. Most of the original city data was taken from

        <a href="http://geonames.org/">Geonames.org</a>.'
    json_Coords:
      type: object
      title: coords
      properties:
        long:
          example: -118.3267434
          description: The longitude part of the coordinates.
          type: number
        lat:
          example: 34.0983425
          description: The latitude part of the coordinates.
          type: number
      example:
        long: -118.3267434
        lat: 34.0983425
      description: Coordinates of a point on the globe. Mostly used for Cities.
